stages:
  - build

build:
  stage: build
  image: python:3.9-slim # Use a Python 3.9 Docker image
  script:
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - pip install pytest
    - pytest tests/
  only:
    - main # Run only on the main branch
